### PR TITLE
Fixed copy buttons

### LINKED ISSUE #2: Botão de copiar não funciona.
Em todas as vezes que o botão de copiar aparece, quando tento apertar, o texto não passa para o meu clipboard. Estou procurando pela origem desse problema e já estou tentando resolvê-lo. Estou disposto a fazer uma Pull Request assim que corrigir o problema.

### PR DESCRIPTION
**Pull request by LuisHDantas**
Fixed issue #2 - text not being copied when copy buttons are clicked when viewing test case

### CODE REVIEW

**Comment by LelioMarcos** [comment]
The IDs 'inputField', 'expectedOutputField' and 'userOutputField' do not exist in the code. In this file, 'inputFiled' has the name 'caseInput' and 'userOutputFiled' is 'outputDiff' (see lines 15 and 29).

**Comment by LelioMarcos** [comment]
Also, the copying routine could be a function, couldn't? It would be something like this:
```js 
function copyButtonRoutine(buttonId, copyFieldId) {
        $(`#${buttonId}`).on('click', function(event) {
            var text = document.getElementById(copyFieldId).textContent;
            var windowsText = text.replace(/\n/g, '\r\n');
            navigator.clipboard.writeText(windowsText).then(function () {
                $(`#${buttonId}`).html("<?php echo __("Copied"); ?>!");
                setTimeout(function () {
                    $(`#${buttonId}`).html("<?php echo __("Copy to Clipboard"); ?>");
                }, 1000);
            }).catch(function (err) {
                console.error('Could not copy text: ', err);
            });
        });
    }
```

**Comment by LuisHDantas** [comment]
I agree that it could be a function, the only reason I did not do that was because I had a few problems trying that. I will work on that!

**Comment by LuisHDantas** [comment]
> The IDs 'inputField', 'expectedOutputField' and 'userOutputField' do not exist in the code. In this file, 'inputFiled' has the name 'caseInput' and 'userOutputFiled' is 'outputDiff' (see lines 15 and 29).

Considering that the data-target-field is "input field" (see line 16), does that not mean that I can use the id from inputField? Could you elaborate on why I should use the id from the line above?
Besides, I used the IDs inputField, [...] that you mentioned and it worked like expected, is there an advantage/need to use the other ones you mentioned?

**Comment by LelioMarcos** [comment]
For some reason, it wasn't working for me when I tried that. Yours is working.

**Comment by LuisHDantas** [comment]
I have just tried changing the IDs like you mentioned too to see if it worked the same way, and for some reason it did not, altough it should work based on what I have read online... But still, thanks for the suggestion, I will work on creating the copyButtonRoutine function and submit a new commit soon!

**Comment by LuisHDantas** [comment]
Function created and tested, should be working fine and the code should be much cleaner now!

**Pull request merged**
